[package]
name = "day02"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part01"
path = "src/part01.rs"

[[bin]]
name = "part02"
path = "src/part02.rs"

[dependencies]
pest = "2.7"
pest_derive = "2.7"
